[workspace]
resolver = "2"
members = [ "genome-kit", "kruskal", "needleman", "phylogeny"]

[profile.release]
debug-symbols = true
opt-level = 3
#lto = true
#codegen-units = 1
#strip = "symbols"
panic = "abort"